###
Script used to process the .tml file that is generated by the timeline SASA calculation in the VMD software. SASA per frame is averaged and given back to the user. This was used to aid in the calculation of SASA for figure 3D and 5C as well as in the x-axis of the KDEL plots for figures 4A and 5D of Kihn et. al., 2021
###

import math
import tkinter.filedialog
import tkinter.simpledialog
import pandas as pd
import os
import numpy as np

file_path = tkinter.filedialog.askdirectory(title='Please select the input file')
save_loc = (tkinter.filedialog.askdirectory(title='Please select the save directory') + '/')

class AvgFile:
    def __init__(self, *args):
        ...


def find_files(file_path):
    file_list = []
    for fname in os.listdir(file_path):
        if fname.endswith(".dat"):
            avg_file = AvgFile()
            fp = str(file_path) + '/' + str(fname)
            df = pd.read_csv(fp, sep='\s+', header=None)
            df.columns = 'Frame', '#', 'Name', 'SASA'
            setattr(avg_file, 'df', df)
            file_list.append(avg_file)
    print(len(file_list))
    return file_list

def get_avg(file_list):
    values = []
    for f in file_list:
        z=0
        for row in f.df.iterrows():
            values.append(f.df.at[z, 'SASA'])
            z = z+1 
    print(len(values))
    avg = sum(values)/len(values)
    with open('avg_SASA.txt', 'w+') as doc:
        doc.write(str(avg))
        doc.close()

file_list = find_files(file_path)
get_avg(file_list)
          

